DROP DATABASE if exists SHOPPABLE;
CREATE DATABASE SHOPPABLE;
USE  SHOPPABLE;


CREATE TABLE USER(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(70) NOT NULL,
	constraint USERNAME_PK primary key ( USERNAME )
);

INSERT INTO USER(USERNAME, PASSWORD) VALUES ('admin', '1234');

commit;